[WIP][RFC] Nhlt plugin and simple plugin interface
alsa-project/alsa-utils pull request #129
Opened 2021-12-21 19:54 UTC by juimonen

Initial something... I need to figure out:

- where to specify which plugins to load/run (nhlt now hard coded)
- where to install the plugins
- how to get the to-be-loaded plugin names and where
- is the "hidden-visibility" gcc flag ok to hide other than .so entrypoint

2021-12-21 21:15 UTC, perexg requested changes

2021-12-21 21:15 UTC, perexg commented on topology/pre-processor.c
> +		for (i = 0; i < plugins->plugin_count; i++)
I would probably prefer to walk thru `Plugins.Preprocess []` list (from the config file) here - resolve the dynamic symbol and call them directly. It does not matter, if you create a list before or handle the plugin error (non-existent etc.) in the middle of processing.

2021-12-21 21:15 UTC, perexg commented on topology/pre-processor.c
> +	path = getenv("ALSA_TOPOLOGY_PLUGINS");
There should be the default path. Something like https://github.com/alsa-project/alsa-plugins/blob/86d695c5d6ba028a3c01758a3b398312408ee0cf/configure.ac#L188 .

`/usr/lib(64)/alsa-topology/` directory may be fine for plugins for example.

2022-01-12 07:54 UTC, juimonen commented on topology/pre-processor.c
> +	strcpy(*xlib, path);
ok

2022-01-12 07:55 UTC, juimonen commented on topology/pre-processor.c
> +		for (i = 0; i < plugins->plugin_count; i++)
ok, this is now changed to do everything in the processing. So init/deinit phase is removed.

2022-01-12 07:57 UTC, juimonen commented
new version:
- plugins are defined in command line or in topology with Define
- plugins are installed in /usr/lib64/alsa-topology, or some other prefix

2022-01-12 07:58 UTC, juimonen commented on topology/pre-processor.c
> +	path = getenv("ALSA_TOPOLOGY_PLUGINS");
ok

2022-01-12 18:11 UTC, ranj063 commented on topology/pre-processor.c
> +	/* first search the command line as the plugins can be defined only there */
is this really needed?The command line defines are merged with the defines in the conf file already no?

2022-01-12 18:11 UTC, ranj063 commented on topology/pre-processor.c
> +	if (xlib == NULL || xfunc == NULL) {
!xlib || !xfunc?

2022-01-12 18:11 UTC, ranj063 commented on topology/pre-processor.c
> +	if (xlib == NULL || xfunc == NULL) {
and don't you have to free xlib if xfunc fails?

2022-01-12 18:11 UTC, ranj063 commented on topology/pre-processor.c
> +		fprintf(stderr, "Unable to run pre-process plugins\n");
run plugins or pre-process plugins?

2022-01-14 13:09 UTC, juimonen commented on topology/pre-processor.c
> +	/* first search the command line as the plugins can be defined only there */
so I was using this so that it would work without the Define in the topology file, so just with command line. Not sure if that's "allowed"... anyway it seems to work.

2022-01-14 13:16 UTC, juimonen commented on topology/pre-processor.c
> +	if (xlib == NULL || xfunc == NULL) {
ok

2022-01-21 16:41 UTC, juimonen commented
@ranj063 @perexg ping for comments for this version?

2022-01-21 16:57 UTC, ranj063 commented on topology/pre-processor.c
> +	/* first search the command line as the plugins can be defined only there */
OK makes sense

2022-01-21 16:57 UTC, ranj063 approved these changes
LGTM @juimonen

2022-01-27 14:05 UTC, perexg commented on topology/pre-processor.c
> +	/* first search the command line as the plugins can be defined only there */
I believe that the initial question has something related. The merge flow for the command line and config file defines is a bit weird now. See pre_process_defines() function - the top argument is not even used! So the call from pre_process_include_conf() seems useless.

I think that the use case when the defines are set only in the command line only is valid, so the "Define" tree should be build too.

I tried to fix that in e1a07113291c240d598f018a8086dcef23003961 and also added small obvious cleanups on top. Please, rebase. With those changes this loop should be removed.

2022-01-27 14:20 UTC, perexg commented on topology/pre-processor.c
> +		ret = snd_config_search(tplg_pp->input_cfg, "Define", &conf_defines);
You can remove the inner loop if you just use `Define.PREPROCESS_PLUGINS` for the snd_config_search*() argument....

2022-01-27 14:21 UTC, perexg commented
It may not be ideal to set the list of required plugins in the `Define` section. It's not much stackable (the string cannot be merged with the included contents  - only one definition wins etc.). But we can add this feature later (new configuration subtree), so pls, drop the loop, optimize the plugins string fetch, test against the latest code in repo and I'll merge.

2022-01-27 16:04 UTC, ranj063 commented on topology/pre-processor.c
> +	/* first search the command line as the plugins can be defined only there */
@perexg I actually need to have the pre-process defines use the "top" argument. I fixed it in my PR https://github.com/alsa-project/alsa-utils/pull/138 but I need to rebase it now. This will allow us to have defines inside the included conf files as well

2022-01-27 17:29 UTC, perexg commented on topology/pre-processor.c
> +	/* first search the command line as the plugins can be defined only there */
My current code does this:

1) merge the included file to the main configuration tree (`tplg_pp->input_cfg`), including the `Define` section 
2) overwrite/merge the `input_cfg.Define` subtree with the command line defines (precedence)

So the behaviour should be similar. You wanted (with the fix):

1) parse `Define` section from the included configuration
2) overwrite/merge with the command line defines
3) merge to the main configuration tree (`input_cfg`), including the updated `Define` section

Just drop your first patch from PR #138.

2022-01-28 14:36 UTC, juimonen commented
@ranj063 @perexg I'm getting this with latest alsa-utils (7245f63b) and our sof topology2 files:
alsatplg: conf.c:2376: snd_config_delete: Assertion `config' failed.

It is segfaulting at the very end of processing when deleting some configs.

I'm running: alsatplg -p -c cavs-nocodec.conf -o test.tplg -v 1

2022-03-29 17:29 UTC, juimonen commented
@perexg we've been testing this quite a bit now, and seems to work for us pretty ok. There could be some issues found of course later....

So please could you check if the plugin mechanism is ok for you (I think that is what you're mostly concerned), I copied stuff to .gitcompile&configure etc. from alsa-lib, but not sure what is the best way to add that stuff.

And if you have time to review and there's comments, I'll try to fix those... and then we should be ready to merge.

2022-04-13 06:08 UTC, juimonen commented
@perexg ping. If you have time to check this... we are already using this in sof internal CI. Thanks!

2022-05-03 11:26 UTC, perexg approved these changes
I merged the latest code with one optimization - 42010cfeba928afcfbd6ef289e9d547c96fdb1cf . Thank you,.

2022-05-03 11:27 UTC, closed without merging

2024-08-01 01:49 UTC, marc-hb commented on gitcompile
> +aclocal $ACLOCAL_FLAGS
This forgot $alsa_m4_flags, fix submitted in:
- #272