OpenBSD (and maybe other *BSDs) support
alsa-project/alsa-utils pull request #186
Opened 2023-01-01 00:43 UTC by jg1uaa

integrated pkgsrc and FreeBSD-ports diff and build test on OpenBSD/NetBSD.

2023-01-02 02:15 UTC, jg1uaa commented
definitions of lseek64_t and off64_t in os_compat.h needs to be deleted when PR #183 will merged

2023-01-23 18:51 UTC, perexg requested changes

2023-01-23 18:51 UTC, perexg commented on include/os_compat.h
> +#if defined(__NetBSD__) || defined(__DragonFly__) || defined(__OpenBSD__) || defined(__FreeBSD__)
The use of 64-bit functions and offsets were removed in 4e3843d0ed9ea7845f5570a1aca542995f91c232 .

2023-01-23 18:51 UTC, perexg commented on include/os_compat.h
> +#define ESTRPIPE EPIPE
For ALSA subsystem, ESTRPIPE has different meaning that EPIPE. What the BSD kernel returns for suspended devices ?

2023-01-23 18:51 UTC, perexg commented on alsaloop/alsaloop.c
> +#ifdef ERESTART
Define RESTART in os_compat.h - I think that  `#define ERESTART EINTR` should work.

2023-01-30 11:34 UTC, jg1uaa commented on include/os_compat.h
> +#if defined(__NetBSD__) || defined(__DragonFly__) || defined(__OpenBSD__) || defined(__FreeBSD__)
Yes, how do I support this (PR #183) change?

2023-01-30 12:10 UTC, jg1uaa commented on include/os_compat.h
> +#define ESTRPIPE EPIPE
At least OpenBSD, accessing to suspended devices will be blocked. 
Regardless the behavior of that situation, alsa-lib uses EPIPE when ESTRPIPE is not defined (since v1.1.1~ https://github.com/alsa-project/alsa-lib/blob/v1.1.1/include/type_compat.h )

2023-01-30 12:34 UTC, jg1uaa commented on alsaloop/alsaloop.c
> +#ifdef ERESTART
currently ERESTART is defined for BSD kernels inside and should be treat as "reserved" for outside.

2023-01-30 19:39 UTC, perexg commented on include/os_compat.h
> +#if defined(__NetBSD__) || defined(__DragonFly__) || defined(__OpenBSD__) || defined(__FreeBSD__)
The lseek64 / off64_t are no longer used. Remove those lines.

2023-01-30 19:39 UTC, perexg commented on alsaloop/alsaloop.c
> +#ifdef ERESTART
Again, move this to os_compat.h header file.

2023-01-31 11:58 UTC, perexg commented on include/os_compat.h
> +#define ESTRPIPE EPIPE
It would be probably better to define ESTRPIPE as ESPIPE for BSD in both utils and lib. The return codes should be different for apps.

2023-02-01 11:41 UTC, jg1uaa commented on include/os_compat.h
> +#define ESTRPIPE EPIPE
now os_compat.h uses ESPIPE when ESTRPIPE is not available.
currently alsa-lib returns EPIPE only (real EPIPE and instead of ESTRPIPE), this change might make no problem.

if this fix is approved, I will send PR for alsa-lib, too.

2023-02-03 12:09 UTC, closed without merging

2023-02-03 12:10 UTC, perexg commented
Merged, but removed `#define _KMEMUSER 1` block. It seems that ERESTART error code is only internal kernel thing for BSD.