topology: pre-process-object: Expand definitions within strings
alsa-project/alsa-utils pull request #189
Opened 2023-01-26 20:10 UTC by jsarha

The second commit description tries to explain what we are doing here. I was in a little bit of hurry when finishing this. I hope everything is in order. At least this should be good enough to start a discussion.

I'll be away from tomorrow afternoon until 2nd of Feb, but @ranj063 should be able to help with this.

Best regards,
Jyri

2023-01-26 20:14 UTC, jsarha commented
@perexg , how does this look?

2023-02-03 11:59 UTC, perexg requested changes

2023-02-03 11:59 UTC, perexg commented on topology/pre-process-object.c
> +	varname_len = strcspn(*stringp, " .-");
I would use `isalnum()` function + `_` (underscore) character to check for the end-of-variable-name to be consistent with https://github.com/alsa-project/alsa-lib/blob/master/src/confeval.c .

Also, `$[VARNAME]` notation may be handled for variables containing other characters.

2023-02-03 11:59 UTC, perexg commented on topology/pre-process-object.c
> +				switch (type) {
Use `snd_config_get_ascii()` function here...

2023-02-03 11:59 UTC, perexg commented on topology/pre-process-object.c
> +	if ((s[0] == '$' && s[1] == '[')) {
Double `((` and `))` ???

2023-02-06 14:43 UTC, jsarha commented
Thanks @perexg for your comments. This new version should address all the comments, yours and mine:
- Handle also $[$VAR_NAME + 1] notation within strings
- Handle anything but alpha numeric and '_' as a delimiter for variable name
- Use snd_config_get_ascii()
- Fix error print in case tplg_evaluate_config_string() fails

2023-02-06 14:49 UTC, closed without merging

2023-02-06 14:49 UTC, perexg commented
Thanks. Merged.