Updated single and double quotes throughout
alsa-project/alsa-utils pull request #215
Opened 2023-05-21 15:41 UTC by wileyhy

This commit:
- Added double quotes to common expansions; removed quotes from strings; 
- Changed REQUIRES to an indexed array and changed the corresponding for loop; 
- Added curly braces where feasibly necessary; 
- Removed a few unnecessary trailing semi-colons; 
- Put URL's in single quotes to prevent any possible expansions, except for within the sed command on line 988. 
- Some logic structures may depend on word splitting, on lines 641, 643, 654, and 667, so I left those as-is for this commit. 
- Double exclamation marks in double quotes allow history expansion which is usually disabled in non-interactive shells, so I left those as-is also.
- Single quoted instances of 'yes' as a parameter value, since it's also a command name, which in certain contexts could be executed.
- Removed quotes from instances of '$?' since it can only expand to an integer and cannot be unset.

Some additional issues for consideration of further efforts (credit: shellcheck):
- variables 'inp' on line 87 and 'KERNEL_RELEASE' on line 418 appear unused;
- https://pastebin.ca is offline

2023-05-21 18:31 UTC, perexg commented
Do not create multiple PRs. You can update original PR (like PR#210) using force push (`git push -f` command) next time.

2023-05-21 19:12 UTC, ossilator requested changes

2023-05-21 19:12 UTC, ossilator commented on alsa-info/alsa-info.sh
> +	SHFILE="$(mktemp -t alsa-info.XXXXXXXXXX)" || exit 1
this just adds visual noise, as it is unnecessary - assignments don't do word splitting. with some old and broken shells it even causes problems.

repeats all over the place.

2023-05-21 19:12 UTC, ossilator commented on alsa-info/alsa-info.sh
> +		if [[ -n "$DIALOG" ]]
pre-existing: there is no need to use a bash-ism here.

2023-05-21 19:12 UTC, ossilator commented on alsa-info/alsa-info.sh
> +				if [[ "$DIALOG_EXIT_CODE" = 0 ]]; then
this is expected to be numerical. if it's empty, then something has gone seriously wrong.

(also excessive bashism)

2023-05-21 19:12 UTC, ossilator commented on alsa-info/alsa-info.sh
> +			if [[ "$DIALOG_EXIT_CODE" = 0 ]]
as above

2023-05-21 19:12 UTC, ossilator commented on alsa-info/alsa-info.sh
> +	if [ -n "$TEMPDIR" ] && [ "$KEEP_FILES" != 'yes' ]; then
there is no reason whatsoever to quote a bare word. the idea that it could be executed "in certain contexts" is completely bogus.

repeats all over the place.

2023-05-21 20:56 UTC, wileyhy commented
I'm sorry. I didn't know how else to do it; so I'll try the way you
suggested.

On Sun, May 21, 2023, 11:31 AM Jaroslav Kysela ***@***.***>
wrote:

> Do not create multiple PRs. You can update original PR (like PR#210) using
> force push (git push -f command) next time.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alsa-project/alsa-utils/pull/215#issuecomment-1556251815>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUF2F2ZNNTSYQLEY42OJEKTXHJNPNANCNFSM6AAAAAAYJPC73Y>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-27 18:56 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +	SHFILE="$(mktemp -t alsa-info.XXXXXXXXXX)" || exit 1
Actually, in bash while variable assignments themselves don't do word splitting, their list of expansions does include command substitution, which does include word splitting unless the command substitution is double quoted.  So it really isn't so cut and dry. As this explanation shows, there is considerable variation:

https://unix.stackexchange.com/questions/97560/are-quotes-needed-for-local-variable-assignment

As you know, local variables can be set to anything. Word splitting depends on the value of IFS, and `mktemp -t` depends on the value of TMPDIR. For example, if TMPDIR was set as...

`declare -x TMPDIR=$'/home/liveuser/my scripts' 
`

...then these variables would contain whitespace (including SHFILE)...

```
+ TEMPDIR='/home/liveuser/my scripts/alsa-info.fgkDlTJCcq'
+ FILE='/home/liveuser/my scripts/alsa-info.fgkDlTJCcq/alsa-info.txt'
+ NFILE='/home/liveuser/my scripts/alsa-info.txt.VxA6dfdxyr'
```

...and then some of these commands would likely fail...

- line 48, wget
- line 49, grep 
- line 50, `[ -s`
- line 70 & 88, cp
- line 73, 80, 90 & 98, rm

...including 100+ instances of...

`./alsa-info.sh: line ###: $FILE: ambiguous redirect
`

More quoting would prevent a lot of these errors.

2023-05-27 19:03 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +		if [[ -n "$DIALOG" ]]
I don't know what "pre-existing" means in this context, but you're correct in that the double quotes aren't strictly necessary between `[[ ... ]]`. Variable expansions within `[[ ... ]]` are automatically treated as though they're double quoted, you can check me on this, but I'd guess that that development probably had something to do reducing errors among `[` and `test` commands that were caused by unexpected white-space and globs.

2023-05-28 18:13 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +	SHFILE="$(mktemp -t alsa-info.XXXXXXXXXX)" || exit 1
So I left the command substitutions double quoted.

2023-05-28 18:16 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +		if [[ -n "$DIALOG" ]]
I removed the double quotes from within the double-bracket-test commands, ie, `[[ ... ]]`.

2023-05-28 18:17 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +				if [[ "$DIALOG_EXIT_CODE" = 0 ]]; then
See comment above, re double quotes.

2023-05-28 18:17 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +			if [[ "$DIALOG_EXIT_CODE" = 0 ]]
See comment above, re double quotes.

2023-05-28 18:21 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +	if [ -n "$TEMPDIR" ] && [ "$KEEP_FILES" != 'yes' ]; then
Single quotes of individual words have been removed.

2023-05-29 10:25 UTC, ossilator commented on alsa-info/alsa-info.sh
> +	SHFILE="$(mktemp -t alsa-info.XXXXXXXXXX)" || exit 1
the outer assignment cares exactly zero about the quoting within the command substitution (this applies to $(); with backticks, nested quoting is essentially unpredictable with legacy shells).

the rules traditionally change when the assignment is actually an argument to a command like `local`; then you'd need to quote the assignment (which i mean literally - you can include the variable and equal sign in the quotes). the quoting rules for the nested command wouldn't be affected by this, either.

2023-05-29 10:28 UTC, ossilator commented on alsa-info/alsa-info.sh
> +		if [[ -n "$DIALOG" ]]
pre-existing means that the "problem" existed before your patch, and if the maintainers felt it worth it, it could be fixed in a separate patch.

the bash-ism is the use of [[ instead of plain [ or test. this doesn't have anything to do with quoting.

2023-05-29 10:31 UTC, ossilator commented on alsa-info/alsa-info.sh
> +				if [[ "$DIALOG_EXIT_CODE" = 0 ]]; then
these are irrelevant considerations, because the known numerical value is assigned just one line above.

2023-05-29 11:12 UTC, ossilator requested changes
please squash the amends and force-push.

if you do the conversion to here-docs, do that in a separate commit. to keep down the churn, you can either do that first and rebase this commit on top, or you take out the hunks that quote $FILE from this commit, and do the conversion on top.

2023-05-29 14:14 UTC, wileyhy commented
Okay. Maybe caring exactly zero is the problem you should really be working on, Oswald.

2023-06-20 23:53 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +	SHFILE="$(mktemp -t alsa-info.XXXXXXXXXX)" || exit 1
On how shell is basically Swiss cheese:
https://unix.stackexchange.com/questions/171346/security-implications-of-forgetting-to-quote-a-variable-in-bash-posix-shells

2023-06-20 23:53 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +		if [[ -n "$DIALOG" ]]
On security and the attitude of "worthlessness:"
https://www.youtube.com/watch?v=bGUVQaBdxKw

2023-06-21 10:19 UTC, ossilator commented on alsa-info/alsa-info.sh
> +	SHFILE="$(mktemp -t alsa-info.XXXXXXXXXX)" || exit 1
i'm quite aware of these pitfalls, and i presume so is perex.
but hardening code that just isn't an attack target at the expense of legibility is no particularly good trade-off.

2023-06-21 10:24 UTC, ossilator commented on alsa-info/alsa-info.sh
> +		if [[ -n "$DIALOG" ]]
that's a relatively good video, but it's tragicomical that that you apparently think its conclusion is relevant here. it's a non-sequitur of epic proportion.

2023-06-23 05:28 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +	SHFILE="$(mktemp -t alsa-info.XXXXXXXXXX)" || exit 1
LOL

2023-07-09 21:45 UTC, wileyhy commented
This PR is just too big, in the "sprawling" sense of the word. Most of the documentation I've read recommends making smaller PRs that can be rolled back more easily if there's any problem (specifically from Pro Git 2ed, by Chacon & Straub, and from Martin Fowler's webpages as I recall), so how about I just close this one and start again with smaller hunks.

2023-07-11 19:37 UTC, wileyhy commented on alsa-info/alsa-info.sh
> +		if [[ -n "$DIALOG" ]]
*sigh* If you don't believe me when I tell you about tangible things, how can you possibly believe if I tell you about non-tangible things?

2023-07-20 02:52 UTC, closed without merging

2023-07-20 02:53 UTC, wileyhy commented
I'm sorry for posting so much nonsense, and I appreciate your input.