topology: nhlt: Fix dmic configuration blob building
alsa-project/alsa-utils pull request #250
Opened 2023-12-27 17:53 UTC by jsarha

The dmic configuration functions are called for each dmic DAI (or FIFO) separately, and each dmic DAI is configured in their own configuration rounds. However, the later configured dmic FIFO may change the common clock diver and thus affect the FIR configuration of the first configured DAI. However, the first configured FIR blob is not touched after it is configured for the first time.

To overcome this problem always check the both FIR configurations, no matter which DAI we are configuring.

Suggested-by: Seppo Ingalsuo <seppo.ingalsuo@linux.intel.com>

2024-01-02 09:45 UTC, jsarha commented
@singalsu , @lrgirdwo , and @ranj063 , please take a look, before I mark this ready for wider audiece review.

2024-01-02 14:35 UTC, singalsu approved these changes
Looks good and all changes work perfectly for me. Thanks for fixing these!

2024-01-02 15:48 UTC, kv2019i requested changes
One potential issue in first patch, see inline.

Also, a bit more clarification where the second patch is needed would help. I get this is needed to simply the dmic rules. Maybe a reference to a PR that would be using this PR would help?

2024-01-02 15:48 UTC, kv2019i commented on topology/nhlt/intel/dmic/dmic-process.c
>  			MIC_CONTROL_PDM_EN_A(1);
typo in commit: clock diver -> clock divider

2024-01-02 15:48 UTC, kv2019i commented on topology/nhlt/intel/dmic/dmic-process.c
> +		 * the configuration of the DAI configurer earlier.
typoe: configurer -> configured

2024-01-02 15:48 UTC, kv2019i commented on topology/pre-process-object.c
> +		}
Shouldn't we "snd_config_delete(*dst)" also in this case won L1623...?

2024-01-02 19:11 UTC, jsarha commented on topology/pre-process-object.c
> +		}
No, I don't think so. The *dst is passed to the caller and it should do what is necessary (however a string value in $[] is probably an error). The reason why I have to delete *dst here is because I reuse *dst to store the result of the defines search and the pointer holding the result of object attribute search may be lost.

2024-01-02 19:13 UTC, jsarha commented on topology/pre-process-object.c
> +		}
Then again a paranoid programmer would check strdup() result and return -ENOMEM in case its NULL. But since this is a commmand line tool, and there is probably some out of memory error produced by libc, I do not think its necessary.

2024-01-02 19:25 UTC, jsarha commented
> One potential issue in first patch, see inline.
> 
> Also, a bit more clarification where the second patch is needed would help. I get this is needed to simply the dmic rules. Maybe a reference to a PR that would be using this PR would help?

Its needed for example when $DMIC0_RATE is used in format topology object's in_rate. That is because those attribute is also used in ibs attrbute value in $[] expression:

https://github.com/thesofproject/sof/blob/98cc1d3da330052ac43f269fdce11aa8d4562cf0/tools/topology/topology2/include/common/audio_format.conf#L235

Without this change its not possible to but DMIC sample rate completely behind a single define.

2024-01-03 13:35 UTC, RanderWang commented on topology/pre-process-object.c
> +		}
could this be a recursive case like
````
 	channels	$CHANNELS
	sample_bits	$channel * 4
	frame_bits	"$[$channels * $sample_bits]"
````

2024-01-03 13:55 UTC, perexg commented on topology/pre-process-object.c
> +		}
Maybe someone may look, if `tplg_evaluate_config_string` may be replaced with `snd_config_evaluate_string` implementation from alsa-lib.

2024-01-03 16:32 UTC, jsarha commented
Changed since previous version. Make a receive call to snd_config_evaluate_string(), instead of just checking for a global define reference.

2024-01-03 16:47 UTC, perexg commented on topology/pre-process-object.c
> +		}
It would be also more elegant to use `snd_config_remove` + `snd_config_delete` combo rather than duplicating the already allocated string.

```
snd_config_t *tmp = *dst;
snd_config_remove(*tmp); // detach from the configuration tree
snd_config_evaluate_string(dst, val, ....);
snd_config_delete(*tmp);
```

2024-01-03 21:29 UTC, jsarha commented
Yet one more version that expands also $-expressions found from defines, e.g. this allows:
```
Define {
	FOO	"$[$BAR * 2]"
	BAR	2
}

Object.Base.foo_bar {
	foo	"$[$FOO * 2]"
	bar	"$[$bar * 2]"
}
```
Where Object.Base.foo_bar.bar would get value 2*2*2*2 = 16.

However, its worth mentioning that our nhlt code, which what we were working on when this need was recognized, is not able to handle $-expressions found from behind a define. This is fixable thou, and I have hackish code to do it, but I am not sure the added complexity is justified just for the sake of completeness. At least I would need to clean it up first.

2024-01-03 22:37 UTC, jsarha commented on topology/pre-process-object.c
> +		}
I am not yet too fluent with snd_config_* -functions, but is the remove necessary in this case, where the *dst is already a product of snd_config_copy()?

2024-01-04 20:17 UTC, ranj063 commented on topology/pre-process-object.c
> +	const char *val;
@jsarha will this still work if you had the object defined like this instead?
```
Object.Base.foo {
	channels	$CHANNELS
	frame_bits	"$[$channels * $sample_bits]"
        sample_bits	$BIT_DEPTH
}
```

2024-01-05 09:25 UTC, jsarha commented on topology/pre-process-object.c
> +	const char *val;
Yes, that works after this change.

This is the original problem the "topology: Expand attribute references inside $[] expressions"-commit is fixing.  E.g.  allow Object.Base.input_audio_format.in_rate be defined as `$DMIC0_RATE`, without breaking input_audio_format.ibs `"$[($in_channels * ($[($in_rate + 999)] / 1000)) * ($in_bit_depth / 8)]"`.

2024-01-05 16:00 UTC, jsarha commented on topology/pre-process-object.c
> +		}
Now that I have read the code back and forth a bit, I am pretty sure the remove is unnecessary for a node, that has just been copied with snd_config_copy(). However, @perexg if you still think that it is good coding practice to add it there, then certainly I will.

2024-01-08 07:25 UTC, RanderWang commented
@jsarha  The 2ch DMIC config can't work, on 4ch, do you know why ?

2024-01-08 13:36 UTC, jsarha commented
> @jsarha The 2ch DMIC config can't work, on 4ch, do you know why ?

Sorry, I do not follow. Some problem in 2ch DMIC nhlt blob generation in a topology that has 4ch DMIC? Can you explain how exactly can trigger this problem?

And if the issue is not directly related to this PR, then it would probably be best to create a SOF issue to track it.

2024-01-09 01:49 UTC, RanderWang commented
> > @jsarha The 2ch DMIC config can't work, on 4ch, do you know why ?
> 
> Sorry, I do not follow. Some problem in 2ch DMIC nhlt blob generation in a topology that has 4ch DMIC? Can you explain how exactly can trigger this problem?
> 
> And if the issue is not directly related to this PR, then it would probably be best to create a SOF issue to track it.

Sorry,  I meant that 2ch DMIC blob can't work.  The generated DMIC blob is still 4ch case

2024-01-09 02:46 UTC, RanderWang commented
I find the reason, thanks.

2024-01-09 16:37 UTC, ranj063 commented on topology/pre-process-object.c
> +	/* the extracted value may contain a nested $-expression */
this can happen only in the case of a variable that points to a object attribute right? So can we move this block inside the previous if block after like 1612?

2024-01-09 17:14 UTC, jsarha commented on topology/pre-process-object.c
> +	/* the extracted value may contain a nested $-expression */
@ranj063 , is there any reason for us to forbid $[]-expressions in the global definitions? I can imagine that could be handy sometimes. If we allow that then we need to check for $[]-strings also in the global definitions.

2024-01-09 17:26 UTC, ranj063 commented on topology/pre-process-object.c
> +	/* the extracted value may contain a nested $-expression */
@jarsha its not that we want to forbid but it's not really useful isn't it? The global definitions are all known prior to building all objects. So, having references to other globals is the only option and that seems futile isn't it?

2024-01-09 20:31 UTC, jsarha commented on topology/pre-process-object.c
> +	/* the extracted value may contain a nested $-expression */
I do think the reprocessor works that way.  The top level definitions are never relsoved for `$`-expression in their own, but only when references to them are found in object attribute values. And when they are resolved there, they can in turn refer to other object attributes found in the same object. E.g. I can define
```
Define {
	MY_OBS_DEF	"$[($out_channels * ($[($out_rate + 999)] / 1000)) * ($out_bit_depth / 8)]"
}
```
And then in 
```
Class.Base."audio_format" {
...
	obs "$MY_OBS_DEF"
}
```
I tested that this work.

I can imagine that there could be some use for some common expressions defined at toplever, relying on generic object attributes, and used in several objects.

2024-01-11 09:09 UTC, jsarha commented on topology/pre-process-object.c
> +	/* the extracted value may contain a nested $-expression */
I can see some sense in that, but if you don't, that is good enough. We can very well live without this "feature". I'll disable it.

2024-01-11 10:42 UTC, jsarha commented
In the latest version I:
- disabled the $-expression resolving if found from global defines
  *  related comments: https://github.com/alsa-project/alsa-utils/pull/250#discussion_r1448529312
- added snd_config_remove(*dst) here https://github.com/jsarha/alsa-utils/blob/6fe2b9ef7fad343bcf3cbe9975060d74b0610f92/topology/pre-process-object.c#L1621
  * related comments: https://github.com/alsa-project/alsa-utils/pull/250#discussion_r1440669944
  * adding remove before delete should never do any harm (but should it be called from snd_config_delete() always?)

2024-01-23 08:55 UTC, singalsu commented
@kv2019i @ranj063 @RanderWang Please re-review this. We can't merge patches to SOF without having these issues fixed.

2024-01-23 16:10 UTC, ranj063 commented
i'm good with this one. Thanks @jsarha

2024-01-23 16:11 UTC, ranj063 approved these changes

2024-01-24 06:50 UTC, RanderWang approved these changes

2024-01-24 17:39 UTC, closed without merging