topology: pre-processor: Introduce extends/overrides keywords for classes
alsa-project/alsa-utils pull request #268
Opened 2024-05-22 17:07 UTC by ranj063

Add 2 new keywords for class definitions to allow new pipeline classes extend the definitions in the base class. This feature is useful for extending previous pipeline class definitions with the addition of one or more widgets without having to duplicate everything in the new class definition.

For example: Consider a pipeline class definition as below. Note that only the widgets & routes are shown here.

Class.Pipeline.mixout-gain-dai-copier-playback {
	Object.Widget {
		mixout."1" {}
		dai-copier."1" {}
		gain."1" {}
		pipeline."1" {}
	}

	Object.Base {
		!route [
			{
				source mixout.$index.1
				sink	gain.$index.1
			}
		]
	}
}

If we want to extend this pipeline with the addition of an eqiir/eqfir, the extends keyword can be used as below:

Class.Pipeline.mixout-gain-eqiir-eqfir-dai-copier-playback {
	extends "mixout-gain-dai-copier-playback"

	Object.Widget {
		eqiir.1 {}
		eqfir.1 {}
	}

	Object.Base {
		!route [
			{
				source gain.$index.1
				sink   eqiir.$index.1
			}
			{
				source eqiir.$index.1
				sink   eqfir.$index.1
			}
		]
	}
}

This allows for defining a new class without having to duplicate everything in the base class and just adding the new widgets/routes that extend the current pipeline definition in the base class. The extends keyword is useful when extending a pipeline while keeping the routes in the base class intact and adding new widgets at the end of the pipeline.

But if we want to modify an existing pipeline class while modifying the order of widgets and/or inserting new widgets, we should use the overridess keyword instead. This allows for adding new widgets to the list of widgets in the base class definition while also allowing overriding the routes to allow inserting the new widgets and reordering the widgets in the base class. For example, if we want to add a drc widget between the gain and the eqiir modules in the above class, we can do the following:

Class.Pipeline.mixout-efx-dai-copier-playback {
	overrides "mixout-gain-eqiir-eqfir-dai-copier-playback"

	Object.Widget {
		drc.1 {}
	}

	Object.Base {
		!route [
			{
				source mixout.$index.1
				sink	gain.$index.1
			}
			{
				source gain.$index.1
				sink	drc.$index.1
			}
			{
				source	drc.$index.1
				sink	eqiir.$index.1
			}
			{
				source	eqiir.$index.1
				sink	eqfir.$index.1
			}
		]
	}
}

Nore that the routess array contains all the routes in the new class definition.

Link: https://github.com/thesofproject/sof/issues/9082

2024-05-22 17:08 UTC, ranj063 commented
@plbossart @lrgirdwo @jsarha FYI

2024-05-22 17:12 UTC, plbossart commented
Thanks @ranj063 
This feature would simplify the life of maintainers and 3rd parties, we have way too much duplication of entire pipelines when we add an additional processing element. The use of tried-and-tested templates that can be simply extended in a nested manner is probably the best thing since we moved over from M4 to topology2!

2024-05-22 17:44 UTC, ranj063 commented
> Could we just work with whole configuration blocks? This feature may be useful for all config parts. Like:
> 
> ```
> SubtreeCopy.AnUniqueId {
>   type override
>   source "Class.Pipeline.mixout-gain-eqiir-eqfir-dai-copier-playback"
>   target "Class.Pipeline.mixout-efx-dai-copier-playback"
>   tree {
>     Object.Widget {
> 	drc.1 {}
>     }
> 
>     Object.Base {
>          !route [
>             ...
>          ]
>     } 
>   }
> }
> ```

@perexg since we'd like to keep the new sub class definitions in separate conf files, the uniqueid might be problematic. But maybe if I make it an array like below, it might be OK.
Subtreecopy [
     {
      ....
     }
] 

Also, can I retain both the extends/overrides type for the subtreecopy to achieve both pipeline extensions and pipeline widget insertion+reordering for Pipeline classes. For other configs, this could work as a generic config block copy.

2024-05-22 18:13 UTC, perexg commented
> @perexg since we'd like to keep the new sub class definitions in separate conf files, the uniqueid might be problematic. But maybe if I make it an array like below, it might be OK. Subtreecopy [ { .... } ]

Unique ID may be like "Pipeline-mixout-efx-dai-copier-playback" so I don't see a problem here. Using [] (arrays) will assign IDs from the index range (0 ... ) automatically.

> Also, can I retain both the extends/overrides type for the subtreecopy to achieve both pipeline extensions and pipeline widget insertion+reordering for Pipeline classes. For other configs, this could work as a generic config block copy.

The merge type for the new tree update may be specified using a field - I proposed `type` in my example.

2024-05-22 18:36 UTC, plbossart commented
Not sure I follow what the uniqueID is, it looks redundant with the target in the suggested example?

````
SubtreeCopy.Pipeline-mixout-efx-dai-copier-playback {
  type override
  source "Class.Pipeline.mixout-gain-eqiir-eqfir-dai-copier-playback"
  target "Class.Pipeline.mixout-efx-dai-copier-playback"
````

2024-05-22 23:40 UTC, ranj063 commented
@perexg I have modifed the PR to define the Subtreecopy keyword now. Please let me know what you think of this. Thanks!

2024-05-23 10:39 UTC, perexg commented
> Not sure I follow what the uniqueID is, it looks redundant with the target in the suggested example?
> 
> ```
> SubtreeCopy.Pipeline-mixout-efx-dai-copier-playback {
>   type override
>   source "Class.Pipeline.mixout-gain-eqiir-eqfir-dai-copier-playback"
>   target "Class.Pipeline.mixout-efx-dai-copier-playback"
> ```

It's just up to the user to create a unique ID scheme. You can compose any string. If you use one key for multiple configs, the last value is used:

```
a.a "1"
a.a "2"
```

The result is that `a.a = "2"` when the configuration tree is parsed.

2024-05-23 10:56 UTC, perexg commented on topology/pre-processor.c
> +		ret = snd_config_merge(tmp, n, override);
Why is this required? Only `source_tree` should be merged to the `target_tree` here.

2024-05-23 10:58 UTC, perexg commented on topology/pre-processor.c
> +	ret = snd_config_search(curr, "Subtreecopy", &subtrees);
We have already special blocks like `CombineArrays`, thus using upper cases in the middle is fine. I would prefer `SubtreeCopy` or `SubTreeCopy` here or even `TreeCopy` or `ConfigCopy` (may be a good alternative).

2024-05-23 11:04 UTC, perexg commented on topology/pre-processor.c
> +			SNDERR("failed to get type for subtree %s\n", id);
O would keep this as optional with a default (`override` ?).

2024-05-23 11:06 UTC, perexg commented on topology/pre-processor.c
> +		ret = snd_config_merge(tmp, n, override);
Probably a missing lookup for the `tree` field before.

2024-05-23 11:07 UTC, perexg commented
Ok, I would remove all class.pipeline specific code. It is not required IMHO. See:

```
Class.Pipeline.mixout-efx-dai-copier-playback {
       Object.Base {
         !route [
            ...
         ]
    }
}

SubtreeCopy.add-to-mixout-efx {
  type override
  source "Class.Pipeline.mixout-gain-eqiir-eqfir-dai-copier-playback.Object.Widget"
  target "Class.Pipeline.mixout-efx-dai-copier-playback.Object.Widget"
}
```

2024-05-23 11:09 UTC, perexg commented on topology/pre-processor.c
> +				SNDERR("failed to get target tree %s\n", target_id);
You should create an empty compound for the given target path (multi id) here.

2024-05-23 20:05 UTC, ranj063 commented on topology/pre-processor.c
> +				SNDERR("failed to get target tree %s\n", target_id);
@perexg I think I have addressed all your comments except this one. Im not clear why I need to create an empty compound here. I'm creating a new conf block with the source tree and the subtree merged with/without override and then I merge the merged tree to the target tree.

2024-05-24 09:10 UTC, perexg commented on topology/pre-processor.c
> +				SNDERR("failed to get target tree %s\n", target_id);
But the target subtree in the top tree may not exist yet and it's not an error. In this case, an empty tree with target_id path should be created to work with it in the merge operation. Probably the easiest implementation is to use `snd_config_load_string` with "<target_id> {}" string as source and merge the result to `top` and do new `snd_config_search` for `target_id` / `target_tree`.

2024-05-24 09:21 UTC, perexg commented
BTW: I like your nested examples. They show the power for the subtree copying.

2024-05-24 09:27 UTC, perexg requested changes

2024-05-24 09:27 UTC, perexg commented on topology/pre-processor.c
> +		ret = snd_config_delete(source_cfg);
`snd_config_delete(subtrees)` does this job for the whole processed `SubTreeCopy` block.  I think that this step is extra.

2024-05-24 09:27 UTC, perexg commented on topology/pre-processor.c
> +			ret = snd_config_delete(type_cfg);
I would recheck all error paths and the resource deallocation in this function. There are many resource leaks IMHO.

2024-05-28 16:38 UTC, ranj063 commented
> The `tree` field removal means data mixup (what if "source" id is a valid id in the copied sub-tree for example?). My proposal was to have SubTreeCopy configuration separated.

@perexg Sorry for the delay, it was a long weekend in the US. I removed the target/source/type fields from the SUbTreeCOpy node explicitly so that if those fields are valid in the subtree being copied, they will be retained.

2024-05-28 16:38 UTC, ranj063 commented on topology/pre-processor.c
> +				SNDERR("failed to get target tree %s\n", target_id);
ack, fixed now

2024-05-28 16:39 UTC, ranj063 commented on topology/pre-processor.c
> +			ret = snd_config_delete(type_cfg);
The only 2 resources allocated are for the temporary target ID and the temporary node while merging the source tree. I think I have freed both of them in the error paths.

2024-05-31 11:53 UTC, perexg commented
> > The `tree` field removal means data mixup (what if "source" id is a valid id in the copied sub-tree for example?). My proposal was to have SubTreeCopy configuration separated.
> 
> @perexg Sorry for the delay, it was a long weekend in the US. I removed the target/source/type fields from the SUbTreeCOpy node explicitly so that if those fields are valid in the subtree being copied, they will be retained.

Yes, but you cannot override them later then. In my eyes, it would be better to keep the source subtree completely separated (although it requires a new tab level).

2024-05-31 15:40 UTC, ranj063 commented
> Yes, but you cannot override them later then. In my eyes, it would be better to keep the source subtree completely separated (although it requires a new tab level).

@perexg I'm not sure I'm following your comment. Could you please elaborate what you're thinking here?

2024-06-10 08:46 UTC, perexg commented
Do not mix SubTreeCopy configuration with the added/modified tree.

```
SubTreeCopy.### {
  type ###
  source ###
  target ###
  tree {
    ### changes here ###
  }
}
```

Vs. your current implementation:

```
SubTreeCopy.### {
  type ###
  source ###
  target ###
  ### changes here ###
}
```

2024-06-10 18:35 UTC, ranj063 commented
> Do not mix SubTreeCopy configuration with the added/modified tree.
> 
> ```
> SubTreeCopy.### {
>   type ###
>   source ###
>   target ###
>   tree {
>     ### changes here ###
>   }
> }
> ```
> 
> Vs. your current implementation:
> 
> ```
> SubTreeCopy.### {
>   type ###
>   source ###
>   target ###
>   ### changes here ###
> }
> ```

Thanks @perexg. Updated now

2024-06-19 16:20 UTC, ranj063 commented
@perexg can I please bother you to have another look at this PR? I've addressed all your comments.

2024-06-21 14:35 UTC, perexg requested changes
Please, do the last little change. Thank you.

2024-06-21 14:35 UTC, perexg commented on topology/pre-processor.c
> +			char *s;
It's too overkill. Just assign `subtree_cfg = NULL` here. The function `snd_config_merge` does nothing when `src == NULL`.

2024-07-12 17:25 UTC, ranj063 commented on topology/pre-processor.c
> +			char *s;
@perexg sorry for the delay. I was out on vacation. Fixed now.

2024-07-22 16:29 UTC, ranj063 commented on topology/pre-processor.c
> +			char *s;
@perexg Could I please request to have a look at the PR again?

2024-08-06 15:43 UTC, ranj063 commented
@perexg Could you please have a look at this again? This will help us update our SOF topologies. Thanks!

2024-08-06 16:35 UTC, closed without merging