Basque translation for Alsa-Utils
alsa-project/alsa-utils pull request #47
Opened 2020-07-26 10:08 UTC by Porrumentzio

Created `po/eu.po` file and edited `po/LINGUAS` adding basque ISO, `eu`.
_______

I included arrow unicode characters (`←, →, ↑, ↓`) and quotation marks (` ' string ' `) in some translations.
I don't know if this will be a problem. If so, say and I will change them.

2020-09-09 13:31 UTC, fitojb requested changes

2020-09-09 13:31 UTC, fitojb commented on po/eu.po
> +# French translation for alsa-utils
Change this to “Basque”

2020-09-09 13:31 UTC, fitojb commented on po/eu.po
> +# Christoph J. Thompson <cjsthompson@gmail.com>, 2011.
Replace this line with your name and email, and the current year

2020-09-09 13:31 UTC, fitojb commented on po/eu.po
> +"Language: fr\n"
And fix the language code

2020-09-09 13:31 UTC, fitojb commented on po/eu.po
> +"Language-Team: French <fr@li.org>\n"
Change this accordingly

2020-09-09 13:31 UTC, fitojb commented on po/eu.po
> +#~ msgid "Warning: format is changed to S16_LE\n"
Use Poedit to remove these obsolete strings

2020-09-09 15:48 UTC, Porrumentzio commented on po/eu.po
> +#~ msgid "Warning: format is changed to S16_LE\n"
Do you suggest me to remove those commented lines? I can do it editing the file, but I don't know how using Poedit.

2020-09-09 16:10 UTC, Porrumentzio commented
I see these problems are because there's not any .pot file of which can be started a new translation .po
It would be good if the .pot-s can be added.

2020-09-10 10:06 UTC, Porrumentzio commented
It's all done now

2020-09-23 02:57 UTC, fitojb approved these changes

2020-10-23 10:00 UTC, perexg commented
Merged in fb2b947d5c828a728aba2e713a4b037bfc675019 . Thanks.

2020-10-23 10:00 UTC, closed without merging