Intro to Topology2.0
alsa-project/alsa-utils pull request #86
Opened 2021-04-28 02:07 UTC by ranj063

Add support for pre-processing Topology2.0 conf file and building the tplg binary.

An example implementation of topology with Topology2.0 can be found here:
https://github.com/thesofproject/sof/pull/3983
Introduction to Topology 2.0
-----

Topology2.0 is a high level keyword extension on top of the existing ALSA
conf topology format designed to:

1) Simplify the ALSA conf topology definitions by providing high level
   "classes" so topology designers need to write less config for common
   object definitions.

2) Allow simple reuse of objects. Define once and reuse (like M4) with
   the ability to alter objects configuration attributes from defaults.

3) Allow data type and value verification. This is not done today and
   frequently crops up in FW bug reports.

Common Topology Classes
-----------------------

Topology today has some common classes that are often reused throughout
with slightly altered configurations. i.e. widgets (components),
pipelines, dais and controls.

Topology2.0 introduces the high level concept of reusable "class" like
definition for a AIF_IN/AIF_OUT type object that can be used to create
topology objects.

Common Topology Attributes
--------------------------
Topology defines a lot of attributes per object with different types
and constraints. Today there is no easy way to validate type or
constraints and this can lead to many hard to find problems in FW at
runtime.

A new keyword "DefineAttribute" has been added to define attribute
type, size, min value, max value, enum_values. This then allows
alsatplg to validate each topology object attribute.

Topology Classes define the list of attributes that they use and
whether the attribute is mandatory, can be overridden by parent users
or is immutable. This also helps alsatplg emit the appropriate errors
for attribute misuse.

Attribute validation
-------------------------
One of the main features of Topology2.0 is the ability to add constraints to
attributes to define a set of valid values, specify min/max values etc in 
the class definition.

Attribute Inheritance
----------------------
One of the key features of Topology2.0 is howthe attribute values are
propagated from a parent object to a child object. This is accomplished
by adding attributes/arguments with the same name for a parent and an
object. By doing so, when creating a child object, the value for the
common attribute is populated from the parent. If the value is provided
in the child object instance, then it overrides the value coming from
the parent.

**ALSA Conf Parser**
----------------

All the changes being proposed and discussed here must be 100%
compliant with the ALSA conf parser. i.e. no syntax changes or
changes to semantics for any existing keyword.

It's intended that there will be NO changes to the ALSA conf parser

2021-04-28 02:08 UTC, ranj063 commented
@perexg @lrgirdwo This is the initial version of the pre-processing layer for Topology2.0 in alsatplg. I'd appreciate some feedback on the overall direction. Thanks!

2021-04-28 07:14 UTC, perexg commented on topology/pre-process-dapm.c
> +int tplg_create_widget_config_template(snd_config_t **wtemplate)
Template functions are almost same. Could we have one universal function which will accept an array of string / type structures as argument to reduce the code ? I believe that it would be more readable. Also, if the template functions are called one time, the array may be defined in (moved to) the caller function to reduce the exported functions.

2021-04-28 07:16 UTC, perexg commented on topology/pre-process-base.c
> +		return ret;
cfg is not deleted here

2021-04-28 07:17 UTC, perexg commented on topology/pre-process-base.c
> +	snd_config_for_each(i, next, item_config) {
Use snd_config_search here?

2021-04-28 07:20 UTC, perexg commented
First of all, thank you for your work and for accepting of my proposals. I like this way of the implementation. I think that we're very close for the merge. I'll did a quick very incomplete review. I'll do further review in next days.

2021-04-28 16:09 UTC, ranj063 commented
> First of all, thank you for your work and for accepting of my proposals. I like this way of the implementation. I think that we're very close for the merge. I'll did a quick very incomplete review. I'll do further review in next days.

Thank you so much for the feedback @perex. I've been thinking about how to unfy the template functions too. I can work on that in the next couple of days along with your other comments.

2021-04-29 16:24 UTC, ranj063 commented on topology/pre-process-dapm.c
> +int tplg_create_widget_config_template(snd_config_t **wtemplate)
@perex I've removed the template functions now. But I pre-defined the array for each class type. I didnt define the array in the caller because the caller is shared for multiple object types.

2021-05-11 17:03 UTC, ranj063 commented
@perex sorry to bug you but I was wondering if you have more feedback for me to address in this PR. I have one open that I need to address and that is regarding adding the computation for automatic attributes in classes. I will add that patch in the next couple of days.

2021-05-13 19:51 UTC, perexg requested changes
I don't have any other comments to the code (except the two things bellow). We can improve it on the go.

Are the memory allocations checked using valgrind or other memory checker / sanitizer ?

2021-05-13 19:51 UTC, perexg commented on topology/pre-process-class.c
> +	first = snd_config_iterator_first(cfg);
The first iterator may be equal to snd_config_iterator_end() here (empty compound).. The class pointer may be invalid then. Please, add a check.

2021-05-13 19:51 UTC, perexg commented on topology/pre-processor.h
> +/* template configs */
I would move the templates neaby the object_build_map[] declaration. I don't see any benefit to have this structure description split to multiple files. But it's just a suggestion - if you have a good reason, I can be convinced.

2021-05-14 04:50 UTC, ranj063 commented
> I don't have any other comments to the code (except the two things bellow). We can improve it on the go.
> 
> Are the memory allocations checked using valgrind or other memory checker / sanitizer ?
> 
> ... and I apologize for the delay, I'm pretty busy with other things these days.

No worries at all. We have verified the memory allocations using valgrind and there are no errors. I will address your comments and push the changes soon.

2021-05-17 16:51 UTC, ranj063 commented on topology/pre-process-class.c
> +	first = snd_config_iterator_first(cfg);
done

2021-05-17 16:54 UTC, ranj063 commented on topology/pre-processor.h
> +/* template configs */
@perex addressed both your comments now. We are adding more complex topologies to test the new parser and we will fix any issues we find along the way.

2021-05-24 16:37 UTC, ranj063 commented
@perexg Can I bother you to please take a look at the updated version? From a basic 2.0 syntax point of view, this PR covers everything. We would like to additional support to the class definition as enhacements after this is merged.

2021-05-25 16:44 UTC, perexg approved these changes
Merged with some cosmetic tab/spaces changes. Thank you for your work. Create a new PR for bug-fixes. Thank you.

2021-05-25 16:44 UTC, closed without merging

2021-05-25 17:05 UTC, ranj063 commented
Thank you so much @perexg. We plan to start using topology 2.0 in the SOF 1.9 release and in preparation for that we will start contributing bug fixes and/or enhancements.